AFS_dtAirThresHi_C.Value=100;
AFS_dtAirThresLo_C.Value=0;
AFS_swtEnaPlsCor_C.Value=Switch_conv.ON;
AFS_facAirNrmPT1_C.Value=99;
AFS_rAirThresLdLo_C.Value=0.8;
AFS_rAirThresIdlLo_C.Value=0.8;
AFS_rAirThresOvrRunLo_C.Value=0.8;
AFS_rAirThresLdHi_C.Value=1.2;
AFS_rAirThresIdlHi_C.Value=1.2;
AFS_rAirThresOvrRunHi_C.Value=1.2;
AFS_swtPlausChkIdl_C.Value=Switch_conv.ON;
AFS_swtPlausChkLd_C.Value=Switch_conv.ON;
AFS_swtPlausChkOvrRun_C.Value=Switch_conv.ON;
AFS_tiSetyDrftMinDebDef_C.Value=20;
AFS_tiSetyDrftMinDebOk_C.Value=20;
AFS_tiSetyDrftMaxDebDef_C.Value=20;
AFS_tiSetyDrftMaxDebOk_C.Value=20;
SigTst_swtAFSVal_C.Value = Switch_conv.ON;

