% Initialize the Dataset for PhyMod_PwrEntryCalc
%
% Copyright (C) 2017-2027, Wuxi Wolffu Auto Tech Co., Ltd., China


%% 


%% Output signal define

PhyMod_pwrClntEntry= Calibration.Signal;
PhyMod_pwrClntEntry.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrClntEntry.Description = 'Engine power entry into the coolant water';
PhyMod_pwrClntEntry.DataType = 'Pwrl';
PhyMod_pwrClntEntry.Min = -214748364;
PhyMod_pwrClntEntry.Max = 214748364;
PhyMod_pwrClntEntry.DocUnits = 'W';
PhyMod_pwrClntEntry.Dimensions = -1;
PhyMod_pwrClntEntry.DimensionsMode = 'fixed';
PhyMod_pwrClntEntry.Complexity = 'real';
PhyMod_pwrClntEntry.SampleTime = -1;
PhyMod_pwrClntEntry.SamplingMode = 'Sample based';
PhyMod_pwrClntEntry.InitialValue = '0';


%% Meansurement signal define

PhyMod_pwrClntEntry_mp= Calibration.Signal;
PhyMod_pwrClntEntry_mp.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrClntEntry_mp.Description = 'Energy dissipated into the coolant';
PhyMod_pwrClntEntry_mp.DataType = 'Pwrl';
PhyMod_pwrClntEntry_mp.Min = -214748364;
PhyMod_pwrClntEntry_mp.Max = 214748364;
PhyMod_pwrClntEntry_mp.DocUnits = 'W';
PhyMod_pwrClntEntry_mp.Dimensions = -1;
PhyMod_pwrClntEntry_mp.DimensionsMode = 'fixed';
PhyMod_pwrClntEntry_mp.Complexity = 'real';
PhyMod_pwrClntEntry_mp.SampleTime = -1;
PhyMod_pwrClntEntry_mp.SamplingMode = 'Sample based';
PhyMod_pwrClntEntry_mp.InitialValue = '0';


PhyMod_pwrLos_mp= Calibration.Signal;
PhyMod_pwrLos_mp.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrLos_mp.Description = 'Total energy loss dissipated in the engine';
PhyMod_pwrLos_mp.DataType = 'Pwrl';
PhyMod_pwrLos_mp.Min = -214748364;
PhyMod_pwrLos_mp.Max = 214748364;
PhyMod_pwrLos_mp.DocUnits = 'W';
PhyMod_pwrLos_mp.Dimensions = -1;
PhyMod_pwrLos_mp.DimensionsMode = 'fixed';
PhyMod_pwrLos_mp.Complexity = 'real';
PhyMod_pwrLos_mp.SampleTime = -1;
PhyMod_pwrLos_mp.SamplingMode = 'Sample based';
PhyMod_pwrLos_mp.InitialValue = '0';


PhyMod_pwrEGLos_mp= Calibration.Signal;
PhyMod_pwrEGLos_mp.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrEGLos_mp.Description = 'Energy lost in the exhaust gas and engine environment';
PhyMod_pwrEGLos_mp.DataType = 'Pwrl';
PhyMod_pwrEGLos_mp.Min = -214748364;
PhyMod_pwrEGLos_mp.Max = 214748364;
PhyMod_pwrEGLos_mp.DocUnits = 'W';
PhyMod_pwrEGLos_mp.Dimensions = -1;
PhyMod_pwrEGLos_mp.DimensionsMode = 'fixed';
PhyMod_pwrEGLos_mp.Complexity = 'real';
PhyMod_pwrEGLos_mp.SampleTime = -1;
PhyMod_pwrEGLos_mp.SamplingMode = 'Sample based';
PhyMod_pwrEGLos_mp.InitialValue = '0';


PhyMod_pwrTheo_mp= Calibration.Signal;
PhyMod_pwrTheo_mp.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrTheo_mp.Description = 'Theoritical supplied power due to supplied amount of fuel';
PhyMod_pwrTheo_mp.DataType = 'Pwrl';
PhyMod_pwrTheo_mp.Min = -214748364;
PhyMod_pwrTheo_mp.Max = 214748364;
PhyMod_pwrTheo_mp.DocUnits = 'W';
PhyMod_pwrTheo_mp.Dimensions = -1;
PhyMod_pwrTheo_mp.DimensionsMode = 'fixed';
PhyMod_pwrTheo_mp.Complexity = 'real';
PhyMod_pwrTheo_mp.SampleTime = -1;
PhyMod_pwrTheo_mp.SamplingMode = 'Sample based';
PhyMod_pwrTheo_mp.InitialValue = '0';


PhyMod_pwrMech= Calibration.Signal;
PhyMod_pwrMech.CoderInfo.StorageClass = 'ExportedGlobal';
PhyMod_pwrMech.Description = 'Mechanical power generated by engine due to current torque';
PhyMod_pwrMech.DataType = 'Pwrl';
PhyMod_pwrMech.Min = -214748364;
PhyMod_pwrMech.Max = 214748364;
PhyMod_pwrMech.DocUnits = 'W';
PhyMod_pwrMech.Dimensions = -1;
PhyMod_pwrMech.DimensionsMode = 'fixed';
PhyMod_pwrMech.Complexity = 'real';
PhyMod_pwrMech.SampleTime = -1;
PhyMod_pwrMech.SamplingMode = 'Sample based';
PhyMod_pwrMech.InitialValue = '0';


%% Calibration value define

PhyMod_pwrEGLos_MAPX = Calibration.Parameter;
PhyMod_pwrEGLos_MAPX.Value = [10 20 30 40 50 60 70 80];
PhyMod_pwrEGLos_MAPX.CoderInfo.StorageClass = 'Custom';
PhyMod_pwrEGLos_MAPX.CoderInfo.CustomStorageClass = 'ConstVolatile';
PhyMod_pwrEGLos_MAPX.Description = '';
PhyMod_pwrEGLos_MAPX.DataType = 'FuelMass_mg_hub';
PhyMod_pwrEGLos_MAPX.Min = -319;
PhyMod_pwrEGLos_MAPX.Max = 319;
PhyMod_pwrEGLos_MAPX.DocUnits = 'mg/hub';


PhyMod_pwrEGLos_MAPY = Calibration.Parameter;
PhyMod_pwrEGLos_MAPY.Value = [1000 1500 2000 2500 3000 4000 5000 6000];
PhyMod_pwrEGLos_MAPY.CoderInfo.StorageClass = 'Custom';
PhyMod_pwrEGLos_MAPY.CoderInfo.CustomStorageClass = 'ConstVolatile';
PhyMod_pwrEGLos_MAPY.Description = '';
PhyMod_pwrEGLos_MAPY.DataType = 'EngSpeed_rpm';
PhyMod_pwrEGLos_MAPY.Min = -12000;
PhyMod_pwrEGLos_MAPY.Max = 12000;
PhyMod_pwrEGLos_MAPY.DocUnits = 'rpm';


PhyMod_pwrEGLos_MAP = Calibration.Parameter;
PhyMod_pwrEGLos_MAP.Value = [4721 9443.627517 14156.0165 18887.25503 23599.64401 28330.88255 33062.12109 37774.51007;
7087.433026 14156.0165 21262.29908 28330.88255 35418.31558 42486.89905 49593.18163 56661.7651;
9443.627517 18887.25503 28330.88255 37774.51007 47218.13758 56661.7651 66124.24217 75549.02013;
11799.82201 23599.64401 35418.31558 47218.13758 59017.95959 70836.63115 82636.45316 94455.12472;
14156.0165 28330.88255 42486.89905 56661.7651 70836.63115 84992.64765 99167.5137 113323.5302;
18887.25503 37774.51007 56661.7651 75549.02013 94455.12472 113323.5302 132210.7852 151116.8898;
23599.64401 47218.13758 70836.63115 94455.12472 118054.7687 141673.2623 165272.9063 188891.3999;
28330.88255 56661.7651 84992.64765 113342.3798 141673.2623 170004.1449 198335.0274 226665.91];
PhyMod_pwrEGLos_MAP.CoderInfo.StorageClass = 'Custom';
PhyMod_pwrEGLos_MAP.CoderInfo.CustomStorageClass = 'ConstVolatile';
PhyMod_pwrEGLos_MAP.Description = '';
PhyMod_pwrEGLos_MAP.DataType = 'Pwrl';
PhyMod_pwrEGLos_MAP.Min = -214748364;
PhyMod_pwrEGLos_MAP.Max = 214748364;
PhyMod_pwrEGLos_MAP.DocUnits = 'W';


%% Fix value define
CALORIFIC_VALUE = fi(42.5,);
VEHMOT_PI = fi(3.1416,);
Epm_numCyl_C = uint8(4);